#!/bin/sh

org='8888'
server_ip='cmdb.easyops-only.com'
proxy_pem='-----BEGIN RSA PRIVATE KEY-----
MIIBPAIBAAJBANICGU2T0YSrUISGqOWJuZxAlehZApeLDeETX3JGnjDb80aaUfup
zcsQBNQ8+gsc5CySp7BpDboFRM3pqTqsXRECAwEAAQJBAM024dTt8lorMeYe1GJg
3/BxKEvA1wiRCEH9tVIs8Z4ZOx0gA6L8KytB4bmr2/H2pJPY3IebLDkSdCSx52aw
1FUCIQDyO/v60CUhYjFeLtyBgxwinNU+37Ecxe+GPfRVdBtfUwIhAN3xSkye6cGP
+PRFItsXw7aJ4Ly/Zx4gplGjt6uc7ZmLAiEAxW38by1MxgvJHvFkya45tUBMUeVx
7nipQ6mlRizOzn8CIQDBV+YmAXoZyVZTVbcbrgQtDMffJc6rDD5XeIwU0EycKQIg
FUlfX4figuWdwqAJXIdUTJpaXWRZbncjBwgDVlKwkPI=
-----END RSA PRIVATE KEY-----'
proxy_pub='-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANICGU2T0YSrUISGqOWJuZxAlehZApeL
DeETX3JGnjDb80aaUfupzcsQBNQ8+gsc5CySp7BpDboFRM3pqTqsXRECAwEAAQ==
-----END PUBLIC KEY-----'
agent_pub='-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANICGU2T0YSrUISGqOWJuZxAlehZApeL
DeETX3JGnjDb80aaUfupzcsQBNQ8+gsc5CySp7BpDboFRM3pqTqsXRECAwEAAQ==
-----END PUBLIC KEY-----'
